// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCluuGfaGUhc8XhtSrUAp_L1LzQfYBEybU',
    appId: '1:252037675639:web:398bef6ae0064afa2da472',
    messagingSenderId: '252037675639',
    projectId: 'agriculture-b0349',
    authDomain: 'agriculture-b0349.firebaseapp.com',
    storageBucket: 'agriculture-b0349.firebasestorage.app',
    measurementId: 'G-MN14KQ06QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYAFOrZGpqTi6HZh4M41_UHNd77DwgRck',
    appId: '1:252037675639:android:f31d6a0137e860732da472',
    messagingSenderId: '252037675639',
    projectId: 'agriculture-b0349',
    storageBucket: 'agriculture-b0349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARikF2MhFhwy4BOZd6PdemKRchhNGNnZQ',
    appId: '1:252037675639:ios:d5ac24e5f6e5b0032da472',
    messagingSenderId: '252037675639',
    projectId: 'agriculture-b0349',
    storageBucket: 'agriculture-b0349.firebasestorage.app',
    iosBundleId: 'com.example.agricultureAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARikF2MhFhwy4BOZd6PdemKRchhNGNnZQ',
    appId: '1:252037675639:ios:d5ac24e5f6e5b0032da472',
    messagingSenderId: '252037675639',
    projectId: 'agriculture-b0349',
    storageBucket: 'agriculture-b0349.firebasestorage.app',
    iosBundleId: 'com.example.agricultureAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCluuGfaGUhc8XhtSrUAp_L1LzQfYBEybU',
    appId: '1:252037675639:web:13b2839e25c9f52b2da472',
    messagingSenderId: '252037675639',
    projectId: 'agriculture-b0349',
    authDomain: 'agriculture-b0349.firebaseapp.com',
    storageBucket: 'agriculture-b0349.firebasestorage.app',
    measurementId: 'G-REKH9XMWXG',
  );
}
